services:
  db:
    image: postgis/postgis:16-master
    container_name: proyecto_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: proyecto_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  tailwind:
    build:
      context: ..
      dockerfile: docker/tailwind/Dockerfile
    container_name: proyecto_tailwind
    volumes:
      - ../src:/admin/src:delegated
      - ../static:/admin/static:delegated
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    restart: "no"
    tty: true
    stdin_open: true

  vite:
    build:
      context: ../../portal
      dockerfile: docker/Dockerfile
    container_name: proyecto_vite
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ../../portal:/portal:delegated
      - vite_node_modules:/portal/node_modules
    networks:
      - app-network
    restart: "no"
    tty: true
    stdin_open: true

  minio:
    image: minio/minio
    container_name: proyecto_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # consola web
    volumes:
      - minio_data:/data
    networks:
      - app-network
    restart: unless-stopped



volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  vite_node_modules:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge